f=open("poem.txt","w")
f.writelines("Don’t be afraid of the dark, little one,\n")
f.writelines("The earth must rest when the day is done.\n")
f.writelines("The sun must be harsh, but moonlight – never!\n")
f.writelines("And those stars will be shining forever and ever,\n")
f.writelines("Be friends with the Night, there is nothing to fear,\n")
f.writelines("Just let your thoughts travel to friends far and near.\n")
f.writelines("By day, it does seem that our troubles won’t cease,\n")
f.writelines("But at night, late at night, the world is at peace.\n")
f.close()
